### PR TITLE
Changed story subject and added some ascii art

### PR DESCRIPTION
**Pull request by floridop**
Changed the subject of your story. You are free to ask me to do any change you like before approving!

### CODE REVIEW

**Review by JosefineFrid — APPROVED** [review]
Thank you for the swan!

**Comment by floridop** [comment]
I'll close this part of the homework, but if there is something else 
you're curious to try and I am available I'll be happy to test.

**Comment by floridop** [comment]
Hi @JosefineFrid 

Accepting the changes is not enough to complete this homework. You as a release manager must perform a merge. I am not sure whether you understood the process, if you have doubts please ask. Please read carefully slides 76-82 having in mind that **you** are the release manager (not me! I am just a contributor) in this scenario B.

**Comment by floridop** [comment]
I'll close this part of the homework, but if there is something else 
you're curious to try and I am available I'll be happy to test.

**Pull request merged**
